# Based on https://github.com/hashicorp/tfc-workflows-github/blob/main/workflows/terraform-cloud.apply-run.workflow.yml
---
name: Terraform Cloud Apply Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  TF_CLOUD_ORGANIZATION: "lmhd"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  apply:
    # should be plenty of time to kick off runs. we don't actually need to wait for an apply
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - aws-sso
          - better-uptime
          - bootstrap-aws_creds-lmhd_root
          - dns
          - tfc-jwt-test
          - vault
          - vault-okta
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.2
        id: create-run
        with:
          workspace: ${{ matrix.workspace }}
